language: python
addons:
  - firefox: latest
python:
  - "3.7.4"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.25.0/geckodriver-v0.25.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.25.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
dist: xenial
services:
  - xvfb
install:
  - pip install -r requirements.txt
script:
  - coverage run manage.py test
after_success:
  - coveralls
deploy:
  provider: heroku
  api_key:
    secure: "39725a8f-2858-44d2-b5e6-a03e1e5f9e8b"
  app: stormy-falls-27162
  on: master-prod
