language: python # => 1
python: # => 2
  - "3.7.4"
services: # => 3
  - sqlite3
env: # => 4
  -DJANGO=1.11.29 DB=sqlite3
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.25.0/geckodriver-v0.25.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.25.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install: # => 5
  - pip install -r requirements.txt
before_script: # => 6
  - python manage.py migrate
script: # => 7
  - python manage.py test lists
